- set_fact:
    tds: "{{ ansible_date_time.epoch }}"

- rds:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    command: create
    backup_retention: "{{ backup_retention }}"
    instance_name: "{{ ansible_user_id }}-{{ db_engine }}-{{ tds }}"
    region: "{{ region }}"
    wait: yes
    wait_timeout: 1200
    db_engine: "{{ db_engine }}"
    size: "{{ db_size }}"
    instance_type: "{{ instance_type }}"
    username: "{{ db_username }}"
    password: "{{ db_password }}"
    db_name: "{{ db_name }}"
    port: "{{ port }}"
    vpc_security_groups: "{{ vpc_security_groups }}"
    publicly_accessible: yes
    subnet: "{{ subnet }}"
    tags:
      Application: ansible-rds
      Description: "{{ ansible_user_id }} RDS {{ db_engine }} {{ tds }}"
  register: rds

- name: retrieve rds endpoint IP
  shell: "dig +short {{ rds.instance.endpoint }} | tail -n 1"
  register: rds_endpoint_ip

- name: create openshift endpoint
  k8s_v1_endpoints:
    name: "rds-{{ tds }}"
    namespace: "{{ namespace }}"
    subsets:
    - addresses:
        - ip: "{{ rds_endpoint_ip.stdout }}"
      ports:
        - port: "{{ port }}"
          name: "{{ db_engine }}"

- name: create openshift service
  k8s_v1_service:
    name: "rds-{{ tds }}"
    namespace: "{{ namespace }}"
    ports:
    - name: "{{ db_engine }}"
      protocol: "TCP"
      port: "{{ port }}"
      target_port: "{{ port }}"
      node_port: 0

- name: retrieve openshift endpoint ip
  shell: "oc get svc -n {{ namespace }} rds-{{ tds }} --no-headers=true | awk '{ print $2 }'"
  register: endpoint_ip

- name: encode bind credentials
  asb_encode_binding:
    fields:
      POSTGRES_HOST: "{{ endpoint_ip.stdout }}"
      POSTGRES_PORT: "{{ port }}"
      POSTGRES_USER: "{{ db_username }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_DB: "{{ db_name }}"
